Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KitapSitesi.Services;
using KitapSitesi.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace KitapSitesi.Controllers
{
    public class BookController : Controller
    {
        private IBookService bookService;
        private ICategoryService categoryService;
        private ICommentService commentService;

        public BookController(IBookService bookService, ICategoryService categoryService, ICommentService commentService)
        {
            this.bookService = bookService;
            this.categoryService = categoryService;
            this.commentService = commentService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var books = bookService.GetBooks();
            return View(books);
        }

        public IActionResult BooksByCategory(int categoryId)
        {
            var books = bookService.GetBooksByCategoryId(categoryId);
            return View(books);
        }


        private List<SelectListItem> getCategoriesForSelect()
        {
            var categories = categoryService.GetCategories();
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            categories.ToList().ForEach(category => selectListItems.Add(new SelectListItem
            {
                Text = category.Name,
                Value = category.Id.ToString()
            }));
            return selectListItems;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddBook()
        {
            List<SelectListItem> selectListItems = getCategoriesForSelect();

            ViewBag.Items = selectListItems;

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult AddBook(Book book)
        {
            if (ModelState.IsValid)
            {
                bookService.AddBook(book);
                return RedirectToAction(nameof(Index));
            }

            List<SelectListItem> selectListItems = getCategoriesForSelect();
            ViewBag.Items = selectListItems;
            return View();

        }

        public IActionResult AddComment()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddComment(Comment comment)
        {

            if (ModelState.IsValid)
            {
                commentService.AddComment(comment);
                return RedirectToAction("Details", new { id = comment.BookId });
            }
            return View();

        }


        public IActionResult DeleteComment(int id)
        {
            var existingComment = commentService.GetCommentById(id);
            if (existingComment == null)
            {
                return NotFound();

            }
            commentService.DeleteComment(existingComment);
            return RedirectToAction(nameof(Details), new { id = existingComment.BookId });

        }

        public IActionResult Delete(int id)
        {
            var existingBook = bookService.GetBookById(id);
            if (existingBook == null)
            {
                return NotFound();

            }
            var existingComments = commentService.GetCommentsByBookId(id);
            foreach (Comment commentDel in existingComments)
            {
                commentService.DeleteComment(commentDel);
            }
            bookService.DeleteBook(existingBook);
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Details(int id)
        {
            var existingBook = bookService.GetBookById(id);
            if (existingBook == null)
            {
                return NotFound();

            }
            string categoryName = categoryService.CategoryById(existingBook.CategoryId);
            ViewBag.item = categoryName;
            return View(existingBook);

        }

        public IActionResult Edit(int id)
        {
            var existingBook = bookService.GetBookById(id);
            if (existingBook == null)
            {
                return NotFound();

            }

            ViewBag.Items = getCategoriesForSelect();
            return View(existingBook);

        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                int affectedRowCount = bookService.EditBook(book);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KitapSitesi.Services;
using KitapSitesi.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace KitapSitesi.Controllers
{
    public class CartController : Controller
    {
        private IBookService bookService;

        public CartController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        public IActionResult Index(string returnUrl)
        {
            var cart = GetCart();
            ViewBag.ReturnUrl = returnUrl;
            return View(cart);
        }


        public IActionResult FinishShopping()
        {
            var cart = GetCart();
            cart.Clear();
            SaveCart(cart);
            return View();
        }

      
        public IActionResult DeleteBookFromCart(int id)
        {
            Cart cart = GetCart();
            cart.RemoveById(id);
            SaveCart(cart);
            return RedirectToAction(nameof(Index), nameof(Cart), new { returnUrl = "Index" });
        }

        [HttpPost]
        public IActionResult AddToCart(int id, string returnUrl)
        {
            var selectedBook = bookService.GetBookById(id);
            if (selectedBook == null)
            {
                return NotFound();
            }

            Cart cart = GetCart() ?? new Cart();
            cart.AddItem(selectedBook, 1);
            SaveCart(cart);
            return RedirectToAction(nameof(Index), nameof(Cart), new { returnUrl = returnUrl });
        }

        Cart GetCart()
        {
            var data = HttpContext.Session.GetString("sepetim");
            if (data == null)
            {
                return null;
            }
            else
            {
                return JsonConvert.DeserializeObject<Cart>(data);
            }

        }

        void SaveCart(Cart cart)
        {
            HttpContext.Session.SetString("sepetim", JsonConvert.SerializeObject(cart));

        }

        public IActionResult PrevFinishShopping()
        {
            var cart = GetCart();
            return View();
        }

    }
}

Views/Shared/_BookCard.cshtml
@model Book
@{
    var request = ViewContext.HttpContext.Request;
    string returnUrlValue = request.QueryString.HasValue ? $"{request.Path}{request.QueryString}" : request.Path.Value;
}
<style>
    /*
    img {
        width: 140px;
        height: 204px;
        object-fit: cover;
    }*/
</style>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<a asp-action="Details" asp-controller="Book" asp-route-id="@Model.Id" class="card" style="margin-left:15px;margin-bottom:5px">
    <img src="@Model.ImageUrl" class="card-img-top" alt="Saat">

    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Author</p>

        <p class="card-text">@System.Math.Round(Model.Price, 2) TL yerine @System.Math.Round(Model.Price * (decimal)(1 - Model.Discount), 2) TL</p>
        <form asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.Id" method="post">
            <input type="hidden" name="=" returnUrl" value="@returnUrlValue" />
            <button type="submit" class="btn btn-primary">Sepete Ekle</button>
        </form>

    </div>
</a>

Views/Shared/_BookDetailPage.cshtml
@model KitapSitesi.Models.Book


<div style=" width: 50%; margin: 0 auto;">
    <style>
        dt {
            float: left;
            clear: left;
            margin-right: 5px;
            font-weight: bold;
        }

        dd {
            margin-left: 0px;
        }
    </style>

    <h2 style="text-align: center;">  @Html.DisplayFor(model => model.Name)</h2>
    <hr />

    <dl>

        <div class="row" style=" width: 50%; margin: 0 auto;">
            <dd class="col-sm-10">
                <img src="@Html.DisplayFor(model => model.ImageUrl)" />
            </dd>
        </div>



        <div class="row">
            <dt>
                Kitap Adı:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </div>

        <div class="row">
            <dt>
                Yazar Adı:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Author)
            </dd>
        </div>

        <div class="row">
            <dt>
                Kategori:
            </dt>
            <dd>
                @ViewBag.item
            </dd>
        </div>

        <div class="row">
            <dt>
                Açıklama:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </div>

        <div class="row">
            <dt>
                Puan:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Rating)
            </dd>

        </div>
        <div class="row">
            <dt>
                Fiyat:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
        </div>
        <div class="row">
            <dt>
                İndirim tutarı:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Discount)
            </dd>
        </div>
    </dl>
</div>

Views/Shared/_BookPagination.cshtml
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Home Page";
    var count = 0;
}
      

<div class="row">
   
    @foreach (var book in Model)
    {
        @if (count != 0 && count % 4 == 0)
        {
        @:</div>
        @:<div class="row" style="padding:5px;">
        }
        <div class="col-3">
            <partial name="_BookCard" model="@book" />
        </div>
        count++;
    }
</div>

<ul class="pagination">
    @for (int i = 1; i <= ViewBag.TotalPages; i++)
    {
        <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Home" asp-route-page="@i" asp-route-catid="@ViewBag.CatId">@i</a></li>
    }


</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bibliotek</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .navbar {
            margin-bottom: 0;
            background-color: #d8a3ee;
            z-index: 9999;
            border: 0;
            font-size: 15px !important;
            line-height: 1.42857143 !important;
            letter-spacing: 4px;
            border-radius: 0;
        }

            .navbar li a, .navbar .navbar-brand {
                color: #fff !important;
            }

        .navbar-nav li a:hover, .navbar-nav li.active a {
            color: #d8a3ee !important;
            background-color: #fff !important;
        }

        .navbar-default .navbar-toggle {
            border-color: transparent;
            color: #fff !important;
        }

        .container-fluid {
            padding-right: 0;
            padding-left: 0;
            margin-right: auto;
            margin-left: auto
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-dark fixed-top navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color: #d8a3ee;">

            <div class="navbar-collapse collapse w-100 order-0 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">

                    <li class="navbar-brand" style="margin-top:3px;" asp-area="" asp-controller="Home" asp-action="Index">
                        Medyatek
                    </li>



                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                    </li>



                </ul>
            </div>

            <div class="navbar-collapse collapse w-100 order-0 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Kategoriler
                        </a>
                        <ul class="dropdown-menu">
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=1>Araştırma-Tarih</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=2>Anı</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=3>Bilim Kurgu</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=4>Biyografi</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=5>Çizgi Roman</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=6>Çocuk</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=7>Dünya Edebiyatı</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=8>Ders/Sınav Kitapları</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=9>Felsefe</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=10>Kişisel Gelişim</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=11>Roman</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=12>Sanat Tarihi</a></li>
                            <li><a style="background-color: #d8a3ee;" asp-controller="Book" asp-action="BooksByCategory" asp-route-categoryId=13>Türk Edebiyatı</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Book" asp-action="Index">Kitapları Düzenle</a>
                        </li>
                    }
                </ul>
            </div>

 

            <div class="navbar-collapse collapse w-100 order-2 order-md-0 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item" >
                        <a asp-area="" asp-controller="Cart" asp-action="Index"><span class="glyphicon glyphicon-shopping-cart"></span>Sepete Git  </a>
                    </li>

                    <li class="nav-item" ><a asp-area="" asp-controller="Account" asp-action="AddUser"><span class="glyphicon glyphicon-user"></span> Üye Ol  </a></li>
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="nav-item" ><a asp-area="" asp-controller="Account" asp-action="Logout"><span class="glyphicon glyphicon-log-out"></span> Çıkış Yap</a></li>

                    }
                    else
                    {
                        <li class="nav-item" ><a asp-area="" asp-controller="Account" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> Giriş Yap</a></li>
                    }

                </ul>
            </div>
        </nav>
    </header>

    <br>
    <br>

    <div class="container-fluid" style="padding:0px;">
        <main role="main" class="pb-3 w-100" style="background-color:powderblue;">
            @RenderBody()
        </main>
    </div>



    <footer class="border-top footer text-muted" style="        background-color: #d8a3ee;
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        font-size: 15px;

">
        <div class="container" style=" color: #fff;

    ">
            &copy; 2021 - Medyatek - İlayda Begüm İzci - <a asp-area="" asp-controller="Home" asp-action="Privacy"> Gizlilik </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>